easy_admin:
    site_name: 'Админ-панель'
    design:
        assets:
            css:
                - 'css/admin.css'
    list:
        max_results: 100
    show:
        max_results: 100
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
