easy_admin:
    site_name: 'Админ-панель'
    design:
        assets:
            css:
                - 'css/admin.css'
        menu:
            - { label: 'Настройки',icon: 'cogs',entity: 'Config'}
    list:
        max_results: 100
    show:
        max_results: 100
    entities:
        Config:
            class: App\Entity\Config
            label: "Параметр"
            list:
                fields:
                    - {property: 'title', label: 'Название параметра'}
                    - {property: 'name', label: 'Системное имя'}
                    - {property: 'value', label: 'Значение параметра'}
            form:
                fields:
                    - {property: 'title', label: 'Название параметра'}
                    - {property: 'name', label: 'Системное имя'}
                    - {property: 'value', label: 'Значение параметра',type: 'textarea'}
