fos_ck_editor:
    input_sync: true
    default_config: simple_config
    configs:
        simple_config:
            allowedContent: true
            autoParagraph: false

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
